# photo micro-service
photo:
 container_name: yula-container
 image: yula
 restart: always
 ports:
  - "8020:8020"
  - "3001"
 command: bash -c " ./photocontroller-1 -configurationfile confclient.json -httpport 8020  2> photocontroller.log& ./photoexif-1 -httpport 3001 -masteruri http://127.0.0.1:8020/register 2> photoexif.log"
