# photo micro-service
photo:
 container_name: yula-container
 image: yula
 restart: always
 volumes:
  - $HOME:/data
 ports:
  - "8020:8020"
  - "3001"
 command: bash -c " ./photo-controller -configurationfile confclient.json -httpport 8020  2> photocontroller.log& ./photo-exif -httpport 3001 -masteruri http://localhost:8020/register 2> photoexif.log"
